EXEC Clinica.importarMedicos 'C:\Users\fede0\Desktop\BDDA\Tp-BDDA\Tp-BDDA\Dataset\Medicos.csv'
EXEC Clinica.importarPrestadores 'C:\Users\fede0\Desktop\BDDA\Tp-BDDA\Tp-BDDA\Dataset\Prestador.csv'
EXEC Clinica.importarSedes 'C:\Users\fede0\Desktop\BDDA\Tp-BDDA\Tp-BDDA\Dataset\Sedes.csv'
EXEC Clinica.ImportarEstudios 'C:\Users\fede0\Desktop\BDDA\Tp-BDDA\Tp-BDDA\Dataset\Centro_Autorizaciones.Estudios clinicos.json'
EXEC Clinica.ImportarPacientes 'C:\Users\fede0\Desktop\BDDA\Tp-BDDA\Tp-BDDA\Dataset\Pacientes.csv'
EXEC Clinica.CrearXML 'OSDE', '2021-01-01', '2021-12-31'
